from enum import Enum

class TokenType(Enum):
    LPAREN = "lparen"
    RPAREN = "rparen"
    QUOTE = "quote"
    DOT = "dot"
    NUMBER = "number"
    STRING = "string"
    IDENTIFIER = "identifier"
    EQUAL = "equal"
    STAR = "star"
    PLUS = "plus"
    MINUS = "minus"
    SLASH = "slash"
    KEYWORD = "keyword"
    WHITESPACE = "whitespace"
    SEMICOLON = "semicolon"
    UNDERSCORE = "underscore"
    COMMA = "comma"
    DEFINE = "define"
    LAMBDA = "lambda"
    BEGIN = "begin"
    GREATER_THAN = "greater_than"
    LESS_THAN = "less_than"
    GREATER_THAN_EQUAL = "greater_than_equal"
    LESS_THAN_EQUAL = "less_than_equal"
    IF = "if"
    BOOLEAN = "boolean"
    AND = "and"
    OR = "or"
    NOT = "not"
    LIST = "list"
    CAR = "car"
    CDR = "cdr"
    CONS = "cons"
    LET = "let"
    EOF = "eof"